### ISSUE TITLE
大佬，我fork你的这个action了，

### ISSUE THREAD

**Issue by man2018** [Gongzigao/OpenWrt-Actions#1]
我怎么样实时获取你的actions的更新呢？

**Comment by Gongzigao** [comment]
我这个是fork（P3TERX大佬）的，大佬项目地址https://github.com/P3TERX/Actions-OpenWrt，你只需要去pan.wezhike.com下载.config和feeds还有diy里面的内容就可以了，大佬教程很详细

**Comment by man2018** [comment]
我还没有完全明白

**Comment by Gongzigao** [comment]
1.你访问P3TERX大佬的项目：https://github.com/P3TERX/Actions-OpenWrt
2.大佬的项目里有一个中文版的介绍，你可以根据步骤走
3.如果你想编译我这边的固件，可以访问pan.wezhike.com下载.config和一个feeds开头的文件，外加2个diy上传到你的项目；
4.根据大佬的教程进行编译就可以了

**Comment by man2018** [comment]
我现在只明白了.config这个文件的作用，feeds的还没明白，
